default: &default
  host: localhost
  port: 5432
  username: afiper
  password: afiper
  adapter: postgresql
  encoding: unicode
  min_messages: WARNING
  pool: 5

development:
  <<: *default
  database: afiper_development

test:
  <<: *default
  database: afiper_test
